apiVersion: django.my.domain/v1alpha1
kind: DjangoUser
metadata:
  name: admin    # must match the existing CR name
spec:
  username: admin
  email:  admin@example.com
  superuser: true
  passwordSecretRef:
    name: admin-password
    key:  password
