# This rule is not used by the project django-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the django.djangooperator.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: django-operator
    app.kubernetes.io/managed-by: kustomize
  name: djangoapp-editor-role
rules:
- apiGroups:
  - django.djangooperator
  resources:
  - djangoapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - django.djangooperator
  resources:
  - djangoapps/status
  verbs:
  - get
