# This rule is not used by the project django-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over django.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: django-operator
    app.kubernetes.io/managed-by: kustomize
  name: djangouser-admin-role
rules:
- apiGroups:
  - django.my.domain
  resources:
  - djangousers
  verbs:
  - '*'
- apiGroups:
  - django.my.domain
  resources:
  - djangousers/status
  verbs:
  - get
