apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: djangouser-operator
  name: djangouser-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: djangouser-operator
subjects:
- kind: ServiceAccount
  name: djangouser-operator-sa
