apiVersion: django.djangooperator/v1alpha1
kind: DjangoUser
metadata:
  labels:
    app.kubernetes.io/name: django-operator
    app.kubernetes.io/managed-by: kustomize
  name: djangouser-sample
spec:
  username: admin
  email:  admin@example.com
  superuser: true
  passwordSecretRef:
    name: admin-password
    key:  password
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
type: Opaque
stringData:
  password: S3cr3tP@ssw0rd1
