apiVersion: django.djangooperator/v1alpha1
kind: DjangoUser
metadata:
  labels:
    app.kubernetes.io/name: django-operator
    app.kubernetes.io/managed-by: kustomize
  name: djangouser-sample
spec:
  # TODO(user): Add fields here
