//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoCelery) DeepCopyInto(out *DjangoCelery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoCelery.
func (in *DjangoCelery) DeepCopy() *DjangoCelery {
	if in == nil {
		return nil
	}
	out := new(DjangoCelery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoCelery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoCeleryList) DeepCopyInto(out *DjangoCeleryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DjangoCelery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoCeleryList.
func (in *DjangoCeleryList) DeepCopy() *DjangoCeleryList {
	if in == nil {
		return nil
	}
	out := new(DjangoCeleryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoCeleryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoCelerySpec) DeepCopyInto(out *DjangoCelerySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoCelerySpec.
func (in *DjangoCelerySpec) DeepCopy() *DjangoCelerySpec {
	if in == nil {
		return nil
	}
	out := new(DjangoCelerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoCeleryStatus) DeepCopyInto(out *DjangoCeleryStatus) {
	*out = *in
	in.Executed.DeepCopyInto(&out.Executed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoCeleryStatus.
func (in *DjangoCeleryStatus) DeepCopy() *DjangoCeleryStatus {
	if in == nil {
		return nil
	}
	out := new(DjangoCeleryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoMigrate) DeepCopyInto(out *DjangoMigrate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoMigrate.
func (in *DjangoMigrate) DeepCopy() *DjangoMigrate {
	if in == nil {
		return nil
	}
	out := new(DjangoMigrate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoMigrate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoMigrateList) DeepCopyInto(out *DjangoMigrateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DjangoMigrate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoMigrateList.
func (in *DjangoMigrateList) DeepCopy() *DjangoMigrateList {
	if in == nil {
		return nil
	}
	out := new(DjangoMigrateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoMigrateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoMigrateSpec) DeepCopyInto(out *DjangoMigrateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoMigrateSpec.
func (in *DjangoMigrateSpec) DeepCopy() *DjangoMigrateSpec {
	if in == nil {
		return nil
	}
	out := new(DjangoMigrateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoMigrateStatus) DeepCopyInto(out *DjangoMigrateStatus) {
	*out = *in
	in.Applied.DeepCopyInto(&out.Applied)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoMigrateStatus.
func (in *DjangoMigrateStatus) DeepCopy() *DjangoMigrateStatus {
	if in == nil {
		return nil
	}
	out := new(DjangoMigrateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoStatic) DeepCopyInto(out *DjangoStatic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoStatic.
func (in *DjangoStatic) DeepCopy() *DjangoStatic {
	if in == nil {
		return nil
	}
	out := new(DjangoStatic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoStatic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoStaticList) DeepCopyInto(out *DjangoStaticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DjangoStatic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoStaticList.
func (in *DjangoStaticList) DeepCopy() *DjangoStaticList {
	if in == nil {
		return nil
	}
	out := new(DjangoStaticList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoStaticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoStaticSpec) DeepCopyInto(out *DjangoStaticSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoStaticSpec.
func (in *DjangoStaticSpec) DeepCopy() *DjangoStaticSpec {
	if in == nil {
		return nil
	}
	out := new(DjangoStaticSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoStaticStatus) DeepCopyInto(out *DjangoStaticStatus) {
	*out = *in
	in.Collected.DeepCopyInto(&out.Collected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoStaticStatus.
func (in *DjangoStaticStatus) DeepCopy() *DjangoStaticStatus {
	if in == nil {
		return nil
	}
	out := new(DjangoStaticStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoUser) DeepCopyInto(out *DjangoUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoUser.
func (in *DjangoUser) DeepCopy() *DjangoUser {
	if in == nil {
		return nil
	}
	out := new(DjangoUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoUserList) DeepCopyInto(out *DjangoUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DjangoUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoUserList.
func (in *DjangoUserList) DeepCopy() *DjangoUserList {
	if in == nil {
		return nil
	}
	out := new(DjangoUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DjangoUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoUserSpec) DeepCopyInto(out *DjangoUserSpec) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoUserSpec.
func (in *DjangoUserSpec) DeepCopy() *DjangoUserSpec {
	if in == nil {
		return nil
	}
	out := new(DjangoUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DjangoUserStatus) DeepCopyInto(out *DjangoUserStatus) {
	*out = *in
	in.Created.DeepCopyInto(&out.Created)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DjangoUserStatus.
func (in *DjangoUserStatus) DeepCopy() *DjangoUserStatus {
	if in == nil {
		return nil
	}
	out := new(DjangoUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}
